### ISSUE TITLE
0.2.2 does not work for me, problem on startup

### ISSUE THREAD

**Issue by Mumin** [zuhito/node-red-contrib-mqtt-broker#10]
In my flow I have configured to brokers, one on 1883 the other on 1884. That worked fine till my latest toolchain updates (node.js, node-red and mqtt-broker)

now I get  EADDRINUSE on startup although port 1883 and 1884 are not in use
log on startup with the error below

if I use version 0.2.1 but with other tools still most recent its running again.

Welcome to Node-RED
===================

1 Mar 01:05:25 - [info] Node-RED version: v0.18.3-git
1 Mar 01:05:25 - [info] Node.js  version: v9.3.0
1 Mar 01:05:25 - [info] Darwin 17.4.0 x64 LE
1 Mar 01:05:25 - [info] Loading palette nodes
global Settings { uib_globalSettings: { userVendorPackages: [ 'vue', 'axios' ], debug: 'verbose' },
  userDir: '/Users/ts/src/node-red/USERSDIRS/user4',
  httpNodeRoot: '/' }
1 Mar 01:05:26 - [info] Dashboard version 2.8.1 started at /ui
1 Mar 01:05:26 - [warn] ------------------------------------------------------
1 Mar 01:05:26 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
1 Mar 01:05:26 - [warn] ------------------------------------------------------
1 Mar 01:05:26 - [info] Settings file  : /Users/ts/src/node-red/USERSDIRS/user4/settings.js
1 Mar 01:05:26 - [info] User directory : /Users/ts/src/node-red/USERSDIRS/user4
1 Mar 01:05:26 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
1 Mar 01:05:26 - [info] Flows file     : /Users/ts/src/node-red/USERSDIRS/user4/flows.json
1 Mar 01:05:26 - [info] Server now running at http://127.0.0.1:1880/
1 Mar 01:05:26 - [info] Starting flows
1 Mar 01:05:26 - [info] UI Builder - Version 1.0.6 started at /vue
1 Mar 01:05:26 - [info] UI Builder - Local file overrides at /Users/ts/src/node-red/USERSDIRS/user4/uibuilder/vue
1 Mar 01:05:26 - [info] [mosca in:MQTT broker 1883] Binding mosca mqtt server on port: undefined
1 Mar 01:05:26 - [info] [mosca in:MQTT broker 1884] Binding mosca mqtt server on port: undefined
1 Mar 01:05:26 - [info] [e-mail in:adfce80d.e08708] Checking IMAP for new messages
1 Mar 01:05:26 - [info] Started flows
1 Mar 01:05:26 - [red] Uncaught Exception:
1 Mar 01:05:26 - Error: listen EADDRINUSE :::1883
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at /Users/ts/src/node-red/USERSDIRS/user4/node_modules/mosca/lib/server.js:219:16
    at makeCall (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:119:7)
    at NoResultsHolder.release (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:67:9)
    at series (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:39:14)
    at Object.eachSeries (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/steed/steed.js:47:5)
    at Server.steed.series.logInfo (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/mosca/lib/server.js:211:13)
    at makeCall (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:117:7)
    at ResultsHolder.release (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:96:9)
    at Server.steed.series.steed.eachSeries.fallback (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/mosca/lib/server.js:204:9)
    at makeCall (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:117:7)
    at ResultsHolder.release (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/fastseries/series.js:96:9)
    at /Users/ts/src/node-red/USERSDIRS/user4/node_modules/ascoltatori/lib/ascoltatori.js:93:9
    at TrieAscoltatore.<anonymous> (/Users/ts/src/node-red/USERSDIRS/user4/node_modules/ascoltatori/lib/abstract_ascoltatore.js:61:7)
    at TrieAscoltatore.emit (events.js:159:13)
    at _addListener (events.js:191:14)
    at TrieAscoltatore.addListener (events.js:240:10)
    at TrieAscoltatore.once (events.js:271:8)

Process finished with exit code 1

**Comment by martin-doyle** [comment]
Yes, there is a settings problem in v0.2.2. Should be fixed with the next pull request.

**Comment by Mumin** [comment]
thanks Martin, that works now.

However, found another bug in 0.2.2:
I am starting two MQTT brokers, one on port 1883 and the other on 1884. That worked fine in 0.2.1 but in 0.2.2 the second ignores the port setting and tries to come up with 1883 as well - which fails with EANINUSE of course.

**Comment by martin-doyle** [comment]
Please give zuhito some time to merge the pull request. It is still open.

**Comment by zuhito** [comment]
@Mumin @martin-doyle Thank you for this. I merged your pull request and publish it on npm repository as version 0.2.3. Cloud you check version 0.2.3?

**Comment by Mumin** [comment]
Thanks Zuhito, works perfect for me now with 0.2.3
