### ISSUE TITLE
Not working can u help

### ISSUE THREAD

**Issue by scargill** [zuhito/node-red-contrib-mqtt-broker#15]
Node Red bang up to date on Raspberry Pi, already have mosquitto so loaded this, changed ports... if I load up the mqtt in node and point to this (as per suggestion in mosca node) and use different port for the in node... Node Red crashes and I get "not deployed"... ie. I'm sure I'm pointing to sensible alternative ports...  I'm leaving the actual broker database as your example, that does not indicate any issues but...  well I'm sure, months ago thid worked but just tried on both a Pi and a K1+ - both the same end result. Help.

**Comment by martin-doyle** [comment]
Can you give us some more detail about the error? What versions do you use (Raspberry, Node, Node-Red, MQTT broker)? If you run node-red -v what error messages do you get? Thank you.

**Comment by scargill** [comment]
None of the software is more than 2 weeks old, version-wise except for Raspbian which is April 2018 version.

 

Raspberry Pi 3 B+ with full Raspbian…. MWTT Broker is Mosquitto. I put your broker on different ports. I’m well familiar with usin MQTT. Does that help?

 

Pete

**Comment by martin-doyle** [comment]
OK. Understood. When node-red crashes what is the console outcome?
I have Mosquitto running on 1883 and node-red-mqtt-broker on 1884. It looks OK:

Welcome to Node-RED

 30 May 17:56:11 - [info] Node-RED version: v0.18.7
 30 May 17:56:11 - [info] Node.js  version: v8.11.2
 30 May 17:56:11 - [info] Linux 3.2.41-042stab127.2 x64 LE
 30 May 17:56:11 - [info] Loading palette nodes
 30 May 17:56:13 - [info] Dashboabash: Welcome: command not found
rd version 2.9.4 started at /ui
 30 May 17:56:13 - [warn] ------------------------------------------------------
 30 May 17:56:13 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node
 30 May 17:56:13 - [warn] ------------------------------------------------------
 30 May 17:56:13 - [info] Settings file  : /home/martin/.node-red/settings.js
 30 May 17:56:13 - [info] User directory : /home/martin/.node-red
bash: 3: command not found
 30 May 17:56:13 - [warn] Projects disabled : editorTheme.projects.enabled=false
 30 May 17:56:13 - [info] Flows file     : /home/martin/.node-red/flows_s17824608.onlinehome-server.info.json
 30 May 17:56:13 - [info] Server now running at http://127.0.0.1:1880/
 30 May 17:56:13 - [warn]

 Your flow credentials file is encrypted using a system-generated key.

 If the system-generated key is lost for any reason, your credentials
 file will not be recoverable, you will have to delete it and re-enter
 your credentials.

 You should set your own key using the 'credentialSecret' option in
 your settings file. Node-RED will then re-encrypt your credentials
 file using your chosen key the next time you deploy a change.

 30 May 17:56:13 - [info] Starting flows
 30 May 17:56:13 - [info] [mosca in:Mosca] Binding mosca mqtt server on port: 1884
 30 May 17:56:13 - [info] Started flows
 30 May 17:56:13 - [info] [mqtt-broker:Mosquitto] Connected to broker: mqtt://localhost:1883
 30 May 17:56:13 - [info] [mqtt-broker:Mosca] Connected to broker: mqtt://localhost:1884

**Comment by scargill** [comment]
Node-Red contunually restartts - I  have the same setup as you not using projects... and Mosca node doesn't crash, it crashes when I put an mqtt input node on the flow using your broker. I've switched to port 1884. Same result,  Node Red loop-crashes until I kill the mqtt input node.

**Comment by martin-doyle** [comment]
I try to reproduce the error. Could you please provide the node-red (console) log, please?

**Comment by scargill** [comment]
node-red

31 May 05:30:20 - [info]

 

Welcome to Node-RED

===================

 

31 May 05:30:20 - [info] Node-RED version: v0.18.5

31 May 05:30:20 - [info] Node.js  version: v6.11.3

31 May 05:30:20 - [info] Linux 4.14.0 arm64 LE

31 May 05:30:21 - [info] Loading palette nodes

31 May 05:30:25 - [info] RedBot version: 0.12.6 (node-red-contrib-chatbot)

node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.

In the future, you will have to enable it yourself.

See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:570:32

31 May 05:30:34 - [info] Dashboard up and running

31 May 05:30:40 - [info] Dashboard version 2.9.4 started at /ui

31 May 05:30:42 - [warn] ------------------------------------------------------

31 May 05:30:42 - [warn] [node-red/rpi-gpio] Info : Ignoring Raspberry Pi specific node

31 May 05:30:42 - [warn] ------------------------------------------------------

31 May 05:30:42 - [info] Settings file  : /home/pi/.node-red/settings.js

31 May 05:30:42 - [info] HTTP Static    : /home/pi/.node-red/public

31 May 05:30:42 - [info] User directory : /home/pi/.node-red

31 May 05:30:42 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable

31 May 05:30:42 - [info] Flows file     : /home/pi/.node-red/flows.json

31 May 05:30:42 - [info] Server now running at http://127.0.0.1:1880/

31 May 05:30:42 - [warn]

 

---------------------------------------------------------------------

Your flow credentials file is encrypted using a system-generated key.

 

If the system-generated key is lost for any reason, your credentials

file will not be recoverable, you will have to delete it and re-enter

your credentials.

 

You should set your own key using the 'credentialSecret' option in

your settings file. Node-RED will then re-encrypt your credentials

file using your chosen key the next time you deploy a change.

---------------------------------------------------------------------

 

31 May 05:30:42 - [info] Starting flows

31 May 05:30:43 - [info] [mosca in:mongodb://127.0.0.1:27107/mqtt] Binding mosca mqtt server on port: 1884

31 May 05:30:43 - [info] Started flows

31 May 05:30:43 - [info] serial port /dev/ttyS1 opened at 57600 baud 8N1

31 May 05:30:43 - [info] [mosca in:mongodb://127.0.0.1:27107/mqtt] Persistence Ready

31 May 05:30:43 - [info] [mqtt-broker:8d48b4b8.799f48] Connected to broker: mqtt://127.0.0.1:1883

 

 



All is well to here

 

As soon as I connect an mqtt input node to 1884

 



Node red shuts down: connecting mqtt to mosquitto at 1883 is fine but not your broker at 1884

**Comment by scargill** [comment]
Andf here is mosca setup

**Comment by martin-doyle** [comment]
Just a question: Do you connect the MQTT In node directly to the MQTT Broker node? How does your flow look like?

**Comment by scargill** [comment]
Yed, the flow has only the two nodes and debug output.

**Comment by martin-doyle** [comment]
"Node-Red dies" means without any exception? It just stops working?
 
If you run `node-red -v` you do not get any message? Usually there is an entry "[red] Uncaught Exception:".

Also if you connect the MQTT broker to a debug node there is no error message?

**Comment by scargill** [comment]
Here it is from starting Node Red then sdding the mqtt input + debug. NR immediately stops. I've run this directly here rather than in my normal startup script. The undefined is something to do with mongodb. to be clear I've never installed mongodb into nr. I'm assuming your broker setup handles that

3 Jun 20:45:27 - [info] Starting flows
3 Jun 20:45:28 - [info] [mosca in:mosca] Binding mosca mqtt server on port: 1884
3 Jun 20:45:28 - [info] Started flows
3 Jun 20:45:28 - [info] serial port /dev/ttyS1 opened at 57600 baud 8N1
3 Jun 20:45:28 - [info] [mosca in:mosca] Persistence Ready
3 Jun 20:45:28 - [info] [mqtt-broker:8d48b4b8.799f48] Connected to broker: mqtt://127.0.0.1:1883
3 Jun 20:46:54 - [info] Stopping modified nodes
3 Jun 20:46:54 - [info] Stopped modified nodes
3 Jun 20:46:54 - [info] Starting modified nodes
3 Jun 20:46:54 - [info] Started modified nodes
3 Jun 20:46:54 - [red] Uncaught Exception:
3 Jun 20:46:54 - TypeError: Cannot read property 'find' of undefined
    at MongoPersistence.lookupSubscriptions (/home/pi/.node-red/node_modules/mosca/lib/persistence/mongo.js:212:22)
    at EventEmitter.restoreClientSubscriptions (/home/pi/.node-red/node_modules/mosca/lib/persistence/abstract.js:103:10)
    at completeConnection (/home/pi/.node-red/node_modules/mosca/lib/client.js:72:17)
    at /home/pi/.node-red/node_modules/mosca/lib/client.js:366:7
    at EventEmitter.Server.authenticate (/home/pi/.node-red/node_modules/mosca/lib/server.js:414:3)
    at Client.handleConnect (/home/pi/.node-red/node_modules/mosca/lib/client.js:337:15)
    at Connection.<anonymous> (/home/pi/.node-red/node_modules/mosca/lib/client.js:146:10)
    at Connection.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.emitPacket (/home/pi/.node-red/node_modules/mqtt-connection/connection.js:13:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Connection.<anonymous> (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at emitReadable_ (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at Connection.Readable.push (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at Writable.dummyWrite [as _write] (/home/pi/.node-red/node_modules/reduplexer/index.js:103:14)
    at doWrite (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/home/pi/.node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/pi/.node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/pi/.node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/pi/.node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
pi@k1plus:~$

**Comment by martin-doyle** [comment]
I am still trying to reproduce the error. So, i installed it on a Solidrun Cubox. Again, it works for me. By the way, I do install my node-red components globally and not in the node-modules folder 
-> `sudo npm install -g --unsafe-perm node-red-contrib-mqtt-broker`.
