### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by Paul-Reed** [zuhito/node-red-contrib-mqtt-broker#2]
I'm running Node-RED version: v0.17.4 and Node.js  version: v6.11.0 on a Raspberry Pi 3.
Tried installing via the pallet manager twice, and the MQTT icon does not appear in the pallet.
Checking the log after a NR server restart, I see the following;

```
16 Aug 19:19:24 - [info] Loading palette nodes
{ Error: Cannot find module '../build/Release/bson'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-mqtt-broker/node_modules/mosca/node_modules/mongodb/node_modules/bson/ext/index.js:15:10
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
16 Aug 19:19:33 - [warn] [mosca in] Deprecated call to RED.runtime.nodes.registerType - node-set name must be provided as first argument
```

**Comment by martin-doyle** [comment]
Could you try the newest version 0.2.3?
