### ISSUE TITLE
Crash when publish topic

### ISSUE THREAD

**Issue by rskhatri** [zuhito/node-red-contrib-mqtt-broker#21]
I am trying to publish value on topic "/test/" and I am getting following crash.

    at MongoPersistence.storeRetained (/usr/src/node-red/node_modules/mosca/lib/persistence/mongo.js:250:20)
    at Server.server.storePacket (/usr/src/node-red/node_modules/mosca/lib/persistence/abstract.js:69:12)
    at Server.publish (/usr/src/node-red/node_modules/mosca/lib/server.js:377:8)
    at Client.handleAuthorizePublish (/usr/src/node-red/node_modules/mosca/lib/client.js:569:17)
    at /usr/src/node-red/node_modules/mosca/lib/client.js:107:14
    at Server.authorizePublish (/usr/src/node-red/node_modules/mosca/lib/server.js:444:3)
    at Connection.<anonymous> (/usr/src/node-red/node_modules/mosca/lib/client.js:106:19)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.emitPacket (/usr/src/node-red/node_modules/mqtt-connection/connection.js:13:8)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.<anonymous> (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at emitNone (events.js:106:13)
    at Connection.emit (events.js:208:7)
    at emitReadable_ (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at Connection.Readable.push (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at Writable.dummyWrite [as _write] (/usr/src/node-red/node_modules/reduplexer/index.js:103:14)
    at doWrite (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/usr/src/node-red/node_modules/reduplexer/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/src/node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/src/node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/src/node-red/node_modules/mqtt-connection/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:106:13)
    at DestroyableTransform.emit (events.js:208:7)

**Comment by martin-doyle** [comment]
Could you provide the full log of Node-Red, please? What system are you using?
